/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package teladeinicio;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Gustavo
 */
public class CadastrarDoencas extends javax.swing.JFrame {
private static final String DB_URL = "jdbc:mysql://localhost:3306/sosrss";
    private static final String DB_USER = "root";
    private static final String DB_PASSWORD = "root";
    /**
     * Creates new form CadastrarDoenças
     */
    public CadastrarDoencas() {
        initComponents();
    }
    private void clearFields() {
        NomeDoencatxt.setText("");
        SintomasTxt.setText("");
        TratamentoTxt.setText("");
        Sobretxt.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPainelCentral = new javax.swing.JPanel();
        jPainelSOSRS = new javax.swing.JPanel();
        jLabelSOSRS = new javax.swing.JLabel();
        jLabelCadastrarDoenças = new javax.swing.JLabel();
        NomeDoencatxt = new javax.swing.JTextField();
        btnCadastrarDoença = new javax.swing.JButton();
        jLabelCadastrarDoenças1 = new javax.swing.JLabel();
        jLabelCadastrarDoenças2 = new javax.swing.JLabel();
        jLabelCadastrarDoenças3 = new javax.swing.JLabel();
        TratamentoTxt = new javax.swing.JTextField();
        Sobretxt = new javax.swing.JTextField();
        SintomasTxt = new javax.swing.JTextField();

        jPainelCentral.setPreferredSize(new java.awt.Dimension(1116, 726));

        jPainelSOSRS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelSOSRS.setFont(new java.awt.Font("Segoe UI Black", 2, 48)); // NOI18N
        jLabelSOSRS.setText("SOSRS");

        javax.swing.GroupLayout jPainelSOSRSLayout = new javax.swing.GroupLayout(jPainelSOSRS);
        jPainelSOSRS.setLayout(jPainelSOSRSLayout);
        jPainelSOSRSLayout.setHorizontalGroup(
            jPainelSOSRSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainelSOSRSLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabelSOSRS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPainelSOSRSLayout.setVerticalGroup(
            jPainelSOSRSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPainelSOSRSLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabelSOSRS)
                .addGap(15, 15, 15))
        );

        jLabelCadastrarDoenças.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabelCadastrarDoenças.setText("NOME DA DOENÇA:");

        btnCadastrarDoença.setText("CADASTRAR");
        btnCadastrarDoença.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarDoençaActionPerformed(evt);
            }
        });

        jLabelCadastrarDoenças1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabelCadastrarDoenças1.setText("TRATAMENTO:");

        jLabelCadastrarDoenças2.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabelCadastrarDoenças2.setText("SOBRE:");

        jLabelCadastrarDoenças3.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabelCadastrarDoenças3.setText("SINTOMAS:");

        javax.swing.GroupLayout jPainelCentralLayout = new javax.swing.GroupLayout(jPainelCentral);
        jPainelCentral.setLayout(jPainelCentralLayout);
        jPainelCentralLayout.setHorizontalGroup(
            jPainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPainelSOSRS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPainelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPainelCentralLayout.createSequentialGroup()
                        .addComponent(jLabelCadastrarDoenças)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeDoencatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPainelCentralLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(btnCadastrarDoença, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPainelCentralLayout.createSequentialGroup()
                        .addComponent(jLabelCadastrarDoenças3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SintomasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPainelCentralLayout.createSequentialGroup()
                        .addComponent(jLabelCadastrarDoenças1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TratamentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPainelCentralLayout.createSequentialGroup()
                        .addComponent(jLabelCadastrarDoenças2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sobretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPainelCentralLayout.setVerticalGroup(
            jPainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainelCentralLayout.createSequentialGroup()
                .addComponent(jPainelSOSRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastrarDoenças)
                    .addComponent(NomeDoencatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastrarDoenças3)
                    .addComponent(SintomasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastrarDoenças1)
                    .addComponent(TratamentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastrarDoenças2)
                    .addComponent(Sobretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnCadastrarDoença, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPainelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPainelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarDoençaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarDoençaActionPerformed
         String nome = NomeDoencatxt.getText();
        String sintomas = SintomasTxt.getText();
        String tratamento = TratamentoTxt.getText();
        String sobre = Sobretxt.getText();

        if (nome.isEmpty() || sintomas.isEmpty() || tratamento.isEmpty() || sobre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
            String sql = "INSERT INTO doencas (nome, sintomas, tratamento, informacoes) VALUES (?, ?, ?, ?)";
            try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                pstmt.setString(1, nome);
                pstmt.setString(2, sintomas);
                pstmt.setString(3, tratamento);
                pstmt.setString(4, sobre);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Doença cadastrada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                clearFields(); // Limpar os campos após o cadastro
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar a doença: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarDoençaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarDoencas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarDoencas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarDoencas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarDoencas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarDoencas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NomeDoencatxt;
    private javax.swing.JTextField SintomasTxt;
    private javax.swing.JTextField Sobretxt;
    private javax.swing.JTextField TratamentoTxt;
    private javax.swing.JButton btnCadastrarDoença;
    private javax.swing.JLabel jLabelCadastrarDoenças;
    private javax.swing.JLabel jLabelCadastrarDoenças1;
    private javax.swing.JLabel jLabelCadastrarDoenças2;
    private javax.swing.JLabel jLabelCadastrarDoenças3;
    private javax.swing.JLabel jLabelSOSRS;
    private javax.swing.JPanel jPainelCentral;
    private javax.swing.JPanel jPainelSOSRS;
    // End of variables declaration//GEN-END:variables
}
